---
include:
  - board: nice_nano//zmk
    shield: clavismacronicenano
    artifact-name: clavismacronicenano-nice-nano

  - board: xiao_ble//zmk
    shield: clavismacroxiao raw_hid_adapter
    artifact-name: clavismacroxiao-xiao-ble-logging