---
include:
  - board: nice_nano//zmk
    shield: clavismacronicenano
    artifact-name: clavismacronicenano-nice-nano

  - board: xiao_ble//zmk
    shield: clavismacroxiao
    snippet: zmk-usb-logging
    artifact-name: clavismacroxiao-xiao-ble-logging