# ============================================================
# ClavisMacro — XIAO nRF52840 Plus
# ============================================================

# USB, Bluetooth y almacenamiento persistente
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_SETTINGS=y

# ============================================================
# AHORRO DE ENERGÍA
# ============================================================

# Entrar en idle después de un minuto.
CONFIG_ZMK_IDLE_TIMEOUT=60000

# ============================================================
# HARDWARE GENERAL
# ============================================================

CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_SPI=y

# ============================================================
# DOS ENCODERS EC11
# ============================================================

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ============================================================
# ST7789 + PANTALLA PERSONALIZADA LVGL
# ============================================================

CONFIG_DISPLAY=y
CONFIG_LED=y
CONFIG_LED_GPIO=y

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# RGB565
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=y

# Widgets usados por clavis_status_screen.c
CONFIG_LV_USE_ARC=y
CONFIG_LV_USE_BAR=y
CONFIG_LV_USE_LABEL=y

# Fuentes usadas por la interfaz
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_24=y

# Memoria adicional para los objetos de la UI 240x240.
# Esta línea faltaba en el firmware que crasheaba.
CONFIG_LV_Z_MEM_POOL_SIZE=16384

CONFIG_LV_USE_THEME_MONO=y
CONFIG_ZMK_DISPLAY_INVERT=y

# ============================================================
# 10 SK6812MINI-E — UNDERGLOW POR SPI
# ============================================================

CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Estado inicial. Los settings guardados pueden reemplazarlo.
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=20

CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=10
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=10

# Para esta prueba permitimos hasta 100%.
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=100

# ============================================================
# PRUEBA RGB
# ============================================================

# Temporalmente, las luces no se apagarán al entrar en idle.
# La pantalla sí se apagará después de 60 segundos.
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n

# Mantener RGB disponible cuando está conectado por USB.
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n