# ============================================================
# ClavisMacro — XIAO nRF52840 Plus
# ============================================================

# USB, Bluetooth y almacenamiento persistente
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_SETTINGS=y

# ============================================================
# AHORRO DE ENERGÍA
# ============================================================

# Tiempo antes de entrar en idle:
# 60000 ms = 1 minuto
CONFIG_ZMK_IDLE_TIMEOUT=60000

# ============================================================
# HARDWARE GENERAL
# ============================================================

CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_SPI=y

# ============================================================
# DOS ENCODERS EC11
# ============================================================

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ============================================================
# PANTALLA ST7789
# ============================================================

CONFIG_DISPLAY=y

# Control del pin BL mediante gpio-leds
CONFIG_LED=y
CONFIG_LED_GPIO=y

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Cola independiente para la pantalla
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096

# Apagar pantalla y backlight al entrar en idle
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# ST7789 RGB565
CONFIG_LV_COLOR_DEPTH_16=y

# Interfaz visible
CONFIG_LV_USE_THEME_MONO=y
CONFIG_ZMK_DISPLAY_INVERT=y

# ============================================================
# 10 SK6812MINI-E
# ============================================================

CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y

CONFIG_ZMK_RGB_UNDERGLOW=y

# No existe un circuito ext-power separado
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Estado inicial
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=20

# Limitar brillo para ahorrar batería
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=40
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=10

# Apagar las LEDs al entrar en idle
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Permitir RGB por USB y batería
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n