# ClavisMacro — ZMK configuration
# nice!nano v2 / SuperMini nRF52840

# Rotary encoder EC11
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# USB and Bluetooth HID
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Save Bluetooth pairings
CONFIG_SETTINGS=y

# Device name
CONFIG_ZMK_KEYBOARD_NAME="ClavisMacro"